const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand()}
const BASE='./assets/';
const stories=[{image:BASE+'story-01.svg',title:'Так хочется потрогать!\nЛучше — с включенным звуком.',sound:BASE+'tkan1.mp3'},{image:BASE+'grass.jpg',title:'Так хочется потрогать!\nЛучше — с включенным звуком.',sound:BASE+'trava2.mp3'},{image:BASE+'sand3.jpg',title:'Так хочется потрогать!\nЛучше — с включенным звуком.',sound:BASE+'pesok3.mp3'}];
const track=document.querySelector('#storyTrack'),progress=document.querySelector('#storyProgress'),counter=document.querySelector('#storyCounter');const sounds=stories.map(s=>{const a=new Audio(s.sound);a.preload='auto';a.loop=true;return a});let index=0,down=false,startX=0,dx=0,story=null;
stories.forEach(s=>{const el=document.createElement('article');el.className='story';el.innerHTML='<div class="press-wrap"><img class="story-photo" src="'+s.image+'" alt="" draggable="false"></div><div class="press-shadow"></div><div class="story-content"><h2 class="story-title">'+s.title.replaceAll('\n','<br>')+'</h2></div>';track.appendChild(el);const p=document.createElement('i');p.innerHTML='<b></b>';progress.appendChild(p)});
function update(){track.style.transform='translate3d('+(-index*100)+'%,0,0)';[...progress.children].forEach((p,i)=>p.classList.toggle('active',i<=index));counter.textContent=String(index+1).padStart(2,'0')+' / 03';sounds.forEach((a,i)=>{if(i!==index){a.pause();a.currentTime=0}})}update();
function point(e){if(!story)return;const r=story.getBoundingClientRect(),x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));story.style.setProperty('--px',x*100+'%');story.style.setProperty('--py',y*100+'%');story.style.setProperty('--rx',(y-.5)*-22+'deg');story.style.setProperty('--ry',(x-.5)*22+'deg');story.style.setProperty('--depth',Math.max(0,1-Math.hypot(x-.5,y-.5)*1.4))}
function startSound(){const a=sounds[index];a.currentTime=0;const p=a.play();if(p)p.catch(()=>{});tg?.HapticFeedback?.impactOccurred('medium')}
track.addEventListener('pointerdown',e=>{down=true;startX=e.clientX;dx=0;story=[...track.children][index];track.setPointerCapture?.(e.pointerId);point(e);story.classList.add('is-pressed');startSound()});track.addEventListener('pointermove',e=>{if(!down)return;dx=e.clientX-startX;if(Math.abs(dx)<55)point(e);track.style.transform='translate3d(calc('+(-index*100)+'% + '+dx+'px),0,0)'});function up(){if(!down)return;down=false;story?.classList.remove('is-pressed');sounds[index].pause();if(Math.abs(dx)>55){if(dx<0&&index<2)index++;else if(dx>0&&index>0)index--}update();story=null}track.addEventListener('pointerup',up);track.addEventListener('pointercancel',up);
