const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand()}
const BASE='./assets/';const stories=[{image:BASE+'story-01.svg',title:'Так хочется потрогать!\nЛучше — с включенным звуком.',sound:BASE+'tkan1.mp3'},{image:BASE+'grass.jpg',title:'Так хочется потрогать!\nЛучше — с включенным звуком.',sound:BASE+'trava2.mp3'},{image:BASE+'sand3.jpg',title:'Так хочется потрогать!\nЛучше — с включенным звуком.',sound:BASE+'pesok3.mp3'}];
const gallery=[BASE+'gallery/55362965963_c670475b61_o.jpg',BASE+'gallery/55362966458_a7fe009864_k.jpg',BASE+'gallery/55408618546_73655e5bf2_b.jpg',BASE+'gallery/55408735368_5bcdbd95c0_b.jpg',BASE+'gallery/55420000651_fc4e00c610_6k.jpg',BASE+'gallery/55425794394_0816329958_o.jpg',BASE+'gallery/55426018275_eb9e50ba27_o.jpg',BASE+'gallery/55428295814_60989fbb19_o.jpg'];
const track=document.querySelector('#storyTrack'),progress=document.querySelector('#storyProgress'),counter=document.querySelector('#storyCounter'),galleryScreen=document.querySelector('#gallery'),storiesScreen=document.querySelector('#stories'),galleryGrid=document.querySelector('#galleryGrid'),galleryCount=document.querySelector('#galleryCount');const sounds=stories.map(s=>{const a=new Audio(s.sound);a.preload='auto';a.loop=true;return a});let index=0,down=false,startX=0,dx=0,story=null,lens=null;
gallery.forEach((src,i)=>{const f=document.createElement('figure');f.innerHTML='<img src="'+src+'" alt="Фото '+(i+1)+'" loading="lazy">';galleryGrid?.appendChild(f)});if(galleryCount)galleryCount.textContent=gallery.length+' фото';
stories.forEach(s=>{const el=document.createElement('article');el.className='story';el.innerHTML='<div class="press-wrap"><img class="story-photo" src="'+s.image+'" alt="" draggable="false"></div><canvas class="press-canvas"></canvas><div class="press-shadow"></div><div class="story-content"><h2 class="story-title">'+s.title.replaceAll('\n','<br>')+'</h2></div>';track.appendChild(el);el._lens=makeLens(el);const p=document.createElement('i');p.innerHTML='<b></b>';progress.appendChild(p)});
function update(){track.style.transform='translate3d('+(-index*100)+'%,0,0)';[...progress.children].forEach((p,i)=>p.classList.toggle('active',i<=index));counter.textContent=String(index+1).padStart(2,'0')+' / 03';sounds.forEach((a,i)=>{if(i!==index){a.pause();a.currentTime=0}})}update();
function haptic(type='medium'){try{tg?.HapticFeedback?.impactOccurred(type)}catch(e){}}
function makeLens(el){const img=el.querySelector('.story-photo'),c=el.querySelector('.press-canvas'),g=c.getContext('2d');let ready=false,x=0,y=0,on=false;const off=document.createElement('canvas'),og=off.getContext('2d');function resize(){const w=el.clientWidth,h=el.clientHeight,d=Math.min(devicePixelRatio||1,2);c.width=w*d;c.height=h*d;off.width=w*d;off.height=h*d;g.setTransform(d,0,0,d,0,0);og.setTransform(d,0,0,d,0,0);if(img.naturalWidth){const scale=Math.max(w/img.naturalWidth,h/img.naturalHeight),dw=img.naturalWidth*scale,dh=img.naturalHeight*scale;og.clearRect(0,0,w,h);og.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh);ready=true}}if(img.complete)resize();else img.addEventListener('load',resize,{once:true});window.addEventListener('resize',resize);function draw(){if(!ready||!on)return;const w=el.clientWidth,h=el.clientHeight,cx=x,cy=y,R=Math.min(w,h)*.055,O=R*1.45,A=28;g.clearRect(0,0,w,h);g.save();g.beginPath();g.arc(cx,cy,O,0,Math.PI*2);g.clip();const step=2;for(let py=Math.max(0,cy-O);py<=Math.min(h,cy+O);py+=step){for(let px=Math.max(0,cx-O);px<=Math.min(w,cx+O);px+=step){const vx=px-cx,vy=py-cy,d=Math.hypot(vx,vy);if(d>O)continue;const fall=Math.pow(1-d/O,3),shift=A*fall;const sx=px+vx/(d||1)*shift,sy=py+vy/(d||1)*shift;g.drawImage(off,sx,sy,step,step,px,py,step,step)}}g.restore()}return{press(px,py){x=px;y=py;on=ready;if(on){c.style.display='block';img.style.opacity='0';draw()}},move(px,py){x=px;y=py;draw()},release(){on=false;c.style.display='none';img.style.opacity='1'}}}
function point(e){if(!story)return;const r=story.getBoundingClientRect();const px=Math.max(0,Math.min(r.width,e.clientX-r.left)),py=Math.max(0,Math.min(r.height,e.clientY-r.top));story.style.setProperty('--px',px/r.width*100+'%');story.style.setProperty('--py',py/r.height*100+'%');story.style.setProperty('--depth',Math.max(0,1-Math.hypot(px/r.width-.5,py/r.height-.5)*1.8));lens?.move(px,py)}function startSound(){const a=sounds[index];a.currentTime=0;const p=a.play();if(p)p.catch(()=>{});haptic('medium')}
track.addEventListener('pointerdown',e=>{down=true;startX=e.clientX;dx=0;story=[...track.children][index];lens=story._lens;track.setPointerCapture?.(e.pointerId);const r=story.getBoundingClientRect(),px=Math.max(0,Math.min(r.width,e.clientX-r.left)),py=Math.max(0,Math.min(r.height,e.clientY-r.top));lens?.press(px,py);point(e);story.classList.add('is-pressed','touch-shake');haptic('medium');startSound()});track.addEventListener('pointermove',e=>{if(!down)return;dx=e.clientX-startX;point(e);track.style.transform='translate3d(calc('+(-index*100)+'% + '+dx+'px),0,0)'});function up(){if(!down)return;down=false;lens?.release();story?.classList.remove('is-pressed','touch-shake');sounds[index].pause();const swiped=Math.abs(dx)>55;if(swiped){if(dx<0&&index<2){index++;update()}else if(dx>0&&index>0){index--;update()}else if(dx<0&&index===2){storiesScreen.classList.remove('active');galleryScreen.classList.add('active');haptic('heavy')}}else update();story=null;lens=null}track.addEventListener('pointerup',up);track.addEventListener('pointercancel',up);